-- 코드를 입력하세요
SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE FROM (
SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
    ,RANK() OVER(ORDER BY PRICE DESC) AS RNK FROM FOOD_PRODUCT)
WHERE RNK=1