-- 코드를 입력하세요
SELECT A.PRODUCT_ID, A.PRODUCT_NAME, SUM(A.PRICE*B.AMOUNT) FROM FOOD_PRODUCT A, FOOD_ORDER B
WHERE A.PRODUCT_ID = B.PRODUCT_ID
AND TO_CHAR(B.PRODUCE_DATE,'YYMM')='2205'
GROUP BY A.PRODUCT_ID, A.PRODUCT_NAME
ORDER BY 3 DESC, 1