-- 코드를 입력하세요
-- SELECT USER_ID, NICKNAME, SUM(PRICE) TOTAL_SALES FROM 
-- USED_GOODS_USER A,USED_GOODS_BOARD B
-- WHERE 1=1
-- AND A.USER_ID = B.WRITER_ID
-- AND B.STATUS = 'DONE'
-- GROUP BY USER_ID, NICKNAME
-- HAVING SUM(PRICE) > 700000
-- ORDER BY SUM(PRICE) ASC

SELECT USER_ID, NICKNAME, SUM(PRICE) TOTAL_SALES FROM 
USED_GOODS_USER A,USED_GOODS_BOARD B
WHERE 1=1
AND A.USER_ID = B.WRITER_ID
AND B.STATUS = 'DONE'
GROUP BY USER_ID, NICKNAME
HAVING SUM(PRICE) >= 700000
ORDER BY SUM(PRICE) ASC